kubectl --namespace default apply -f - <<< '
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: king-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://king-oauth2-proxy.default.svc.cluster.local:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  rules:
    - host: mapgramm.ru
      http:
        paths:
          - path: /king
            pathType: Prefix
            backend:
              service:
                name: king
                port:
                  number: 80
  ingressClassName: nginx
'
